name: "Dummy scale Set"

on:
  workflow_dispatch:
    inputs:
      sleep_time:
        description: "sleep for"
        default: 60
      scale_set:
        description: "scale set name"
        default: test-scale-set

jobs:
  dummy:
    name: "Do nothing, really"

    runs-on:
      - "${{ github.event.inputs.scale_set }}"

    steps:
      - name: "Just print some info"
        shell: bash
        run: |
          hostname
          uname -a
          df -h
          whoami
          sleep ${{ github.event.inputs.sleep_time }}
